apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-nodeport
  namespace: {{ .Values.common.namespace}}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name}}
  ports:
  - port: {{ .Values.nodePort.ports.port}}
    targetPort: {{ .Values.nodePort.ports.targetPort}}
    nodePort: {{ .Values.nodePort.ports.nodePort}}
    protocol: {{ .Values.nodePort.ports.protocol}}