
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: {{ .Values.common.namespace}}
spec:
  volumeName: {{ .Values.pvc.volumeName}}
  accessModes:
    - {{ .Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage}}