apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Values.common.namespace}}
spec:
  strategy:
    type: {{ .Values.todoapp.strategy.type}}
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.strategy.rollingUpdate.maxSurge}}
      maxUnavailable: {{ .Values.todoapp.strategy.rollingUpdate.maxUnavailable}}
  selector:
    matchLabels:
      app: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name}}
    spec:
      serviceAccountName: {{ .Values.rbac.name}}
      containers:
      - name: {{ .Chart.Name}}
        image: {{ .Values.todoapp.repo}}:{{ .Values.todoapp.version}}
        volumeMounts:
        - name: {{ .Values.todoapp.volumeMounts.data.name}}
          mountPath: {{ .Values.todoapp.volumeMounts.data.mountPath | quote}}
        - name: {{ .Values.todoapp.volumeMounts.app_secrets_volume.name}}
          mountPath: {{ .Values.todoapp.volumeMounts.app_secrets_volume.mountPath | quote}}
          readOnly: {{ .Values.todoapp.volumeMounts.app_secrets_volume.readOnly}}
        - name: {{ .Values.todoapp.volumeMounts.app_config_volume.name}}
          mountPath: {{ .Values.todoapp.volumeMounts.app_config_volume.mountPath | quote}}
          readOnly: {{ .Values.todoapp.volumeMounts.app_config_volume.readOnly}}
        resources:
          requests:
            memory: {{ .Values.todoapp.resources.requests.memory}}
            cpu: {{ .Values.todoapp.resources.requests.cpu}}
          limits:
            memory: {{ .Values.todoapp.resources.limits.memory}}
            cpu: {{ .Values.todoapp.resources.limits.cpu}}
        env:
        {{- range .Values.todoapp.env }}
        - name: {{ .name }}
          {{ if .configMapKey }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Chart.Name}}-config
              key: {{ .configMapKey }}
          {{ else if .secretKey }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name}}-secret
              key: {{ .secretKey }}
          {{ end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.todoapp.containerPort}}
        livenessProbe:
          httpGet:
            path: {{ .Values.todoapp.livenessProbe.path}}
            port: {{ .Values.todoapp.containerPort}}
          initialDelaySeconds: {{ .Values.todoapp.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.todoapp.livenessProbe.periodSeconds}}
        readinessProbe:
          httpGet:
            path: {{ .Values.todoapp.readinessProbe.path}}
            port: {{ .Values.todoapp.containerPort}}
          initialDelaySeconds: {{ .Values.todoapp.readinessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.todoapp.readinessProbe.periodSeconds}}
      volumes:
      - name: {{ .Values.todoapp.volumes.data.name}}
        {{ .Values.todoapp.volumes.data.claimType}}:
          claimName: {{ .Values.todoapp.volumes.data.claimName}}
      - name: {{ .Values.todoapp.volumeMounts.app_secrets_volume.name}}
        secret:
          secretName: {{ .Chart.Name}}-secret
      - name: {{ .Values.todoapp.volumeMounts.app_config_volume.name}}
        configMap:
          name: {{ .Chart.Name}}-config
      affinity:
        nodeAffinity:
          {{ .Values.todoapp.nodeAffinity.behavior}}:
            - weight: {{ .Values.todoapp.nodeAffinity.weight }}
              preference:
                matchExpressions:
                  - key: {{ .Values.todoapp.nodeAffinity.key }}
                    operator: {{ .Values.todoapp.nodeAffinity.operator }}
                    values:
                      - {{ .Chart.Name }}
